#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///
"""Render ROADMAP.md (explanatory Mermaid dependency graph + task table) from tasks.yaml.

Usage: roadmap.py [project-root]   (default: nearest project root from cwd)
Deterministic, no LLM involved. Safe to re-run any time.
"""
from __future__ import annotations

import html
import re
import sys
import textwrap
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import (  # noqa: E402
    WorkflowError, find_project_root, git, hold_lock, load_tasks, migrate_project_state,
    project_lock_path, write_text_atomic,
)

STATUS_CLASS = {"pending": "pending", "active": "active", "blocked": "blocked",
                "done": "done", "dropped": "dropped"}
STATUS_BADGE = {"pending": "⬜ pending", "active": "🔵 active", "blocked": "⛔ blocked",
                "done": "✅ done", "dropped": "🚫 dropped"}

CLASS_DEFS = """\
    classDef pending fill:#f5f5f5,stroke:#9e9e9e,color:#424242
    classDef active fill:#bbdefb,stroke:#1565c0,color:#0d2b56,stroke-width:2px
    classDef blocked fill:#ffcdd2,stroke:#c62828,color:#7f1d1d
    classDef done fill:#c8e6c9,stroke:#2e7d32,color:#1b4332
    classDef dropped fill:#eeeeee,stroke:#bdbdbd,color:#9e9e9e,stroke-dasharray: 4 4"""


def node_id(task_id: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", task_id)


def node_label(task: dict) -> str:
    """Bold id + wrapped explanatory title, so an outsider can read the graph."""
    title = html.escape(str(task.get("title", "")), quote=False).replace('"', "'")
    wrapped = "<br/>".join(textwrap.wrap(title, width=26)) or title
    return f'"<b>{task["id"]}</b><br/>{wrapped}"'


def render(root: Path) -> str:
    data = load_tasks(root)
    tasks = [t for t in data.get("tasks", []) if isinstance(t, dict) and t.get("id")]
    milestones = [m for m in data.get("milestones", []) if isinstance(m, dict) and m.get("id")]
    project = data.get("project", root.name)

    by_ms: dict[str | None, list[dict]] = {}
    for t in tasks:
        by_ms.setdefault(t.get("milestone"), []).append(t)

    lines = ["flowchart TD"]
    for ms in milestones:
        group = by_ms.pop(ms["id"], [])
        if not group:
            continue
        ms_title = html.escape(str(ms.get("title", "")), quote=False).replace('"', "'")
        lines.append(f'    subgraph {ms["id"]}["{ms["id"]} — {ms_title} ({ms.get("status", "pending")})"]')
        for t in group:
            lines.append(f"        {node_id(t['id'])}[{node_label(t)}]")
        lines.append("    end")
    backlog = [t for g in by_ms.values() for t in g]
    if backlog:
        lines.append('    subgraph backlog["(no milestone)"]')
        for t in backlog:
            lines.append(f"        {node_id(t['id'])}[{node_label(t)}]")
        lines.append("    end")

    ids = {t["id"] for t in tasks}
    for t in tasks:
        for d in t.get("deps", []):
            if d in ids:
                lines.append(f"    {node_id(d)} --> {node_id(t['id'])}")

    lines.append(CLASS_DEFS)
    by_status: dict[str, list[str]] = {}
    for t in tasks:
        cls = STATUS_CLASS.get(t.get("status", "pending"), "pending")
        by_status.setdefault(cls, []).append(node_id(t["id"]))
    for cls, nodes in by_status.items():
        lines.append(f"    class {','.join(nodes)} {cls}")
    mermaid = "\n".join(lines)

    counts = {s: 0 for s in STATUS_BADGE}
    for t in tasks:
        counts[t.get("status", "pending")] = counts.get(t.get("status", "pending"), 0) + 1
    total = len(tasks)
    done = counts.get("done", 0)
    head = git(root, "rev-parse", "--short", "HEAD") or "n/a"
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    rows = ["| ID | Title | Status | Round | Deps | Anchor |",
            "|---|---|---|---|---|---|"]
    order = {"active": 0, "blocked": 1, "pending": 2, "done": 3, "dropped": 4}
    for t in sorted(tasks, key=lambda t: (order.get(t.get("status", "pending"), 9), t["id"])):
        deps = ", ".join(t.get("deps", [])) or "—"
        rows.append(
            f"| `{t['id']}` | {t.get('title', '')} | {STATUS_BADGE.get(t.get('status', 'pending'))} "
            f"| {t.get('round', '—')} | {deps} | {t.get('anchor', '—')} |"
        )

    return f"""<!-- GENERATED by waystone (roadmap.py) — DO NOT EDIT.
     Source of truth: tasks.yaml. Regenerated automatically on tasks.yaml edits. -->
# Roadmap — {project}

**Progress:** {done}/{total} done · {counts.get('active', 0)} active · {counts.get('blocked', 0)} blocked · generated {now} @ `{head}`

```mermaid
{mermaid}
```

## Tasks

{chr(10).join(rows)}
"""


def main() -> int:
    root = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else find_project_root(Path.cwd())
    if root is None or not (root / "tasks.yaml").is_file():
        print("roadmap: no initialized project (missing .waystone.yml / tasks.yaml)", file=sys.stderr)
        return 1
    try:
        with hold_lock(project_lock_path(root)):
            migrate_project_state(root)
        with hold_lock(project_lock_path(root)):
            out = root / "ROADMAP.md"
            write_text_atomic(out, render(root))
            print(f"wrote {out}")
            return 0
    except WorkflowError as e:
        print(e, file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
