#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///
"""SSOT helper: byte-exact section split, navigation INDEX, compact DIGEST, staleness check.

Usage:
  ssot.py split  [project-root]   # regenerate <generated_dir>/ from the SSOT (sections/INDEX/DIGEST/.hash)
  ssot.py digest [project-root]   # alias of split (kept for back-compat): full regenerate
  ssot.py check  [project-root]   # exit 0 if EVERY generated view matches the SSOT, 3 if any stale/missing/extra

A single pure builder (`build_views`) is the source of truth for split, check, and round-close, so
they can never disagree (e.g. a fresh `.hash` over a stale DIGEST). The canonical document stays a
single editable file; everything here is a generated, read-only view that concatenates back to the
original byte-for-byte (verified).
"""
from __future__ import annotations

import hashlib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import WorkflowError, find_project_root, load_config, slugify  # noqa: E402

GENERATED_NOTE = "<!-- GENERATED by waystone (ssot.py) — DO NOT EDIT. Edit the SSOT instead. -->"


def _ssot_path(root: Path, cfg: dict) -> Path:
    ssot = cfg.get("ssot")
    if not ssot:
        raise WorkflowError("no 'ssot' path in .waystone.yml")
    p = root / ssot
    if not p.is_file():
        raise WorkflowError(f"SSOT not found: {p}")
    return p


def _sections(text: str) -> list[tuple[str, int, str]]:
    """Split on level-2 headings. Returns [(heading, start_line_1based, content)]."""
    lines = text.splitlines(keepends=True)
    bounds: list[int] = [i for i, ln in enumerate(lines) if ln.startswith("## ")]
    sections: list[tuple[str, int, str]] = []
    prev = 0
    heading = "(preamble)"
    for b in bounds:
        if b > prev or prev == 0:
            chunk = "".join(lines[prev:b])
            if chunk:
                sections.append((heading, prev + 1, chunk))
        heading = lines[b].removeprefix("## ").strip()
        prev = b
    sections.append((heading, prev + 1, "".join(lines[prev:])))
    return sections


def _hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _first_paragraph(content: str) -> str:
    """First prose paragraph after the heading line (skips blank lines and code fences)."""
    lines = content.splitlines()
    para: list[str] = []
    in_fence = False
    for ln in lines[1:]:
        if ln.lstrip().startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        if ln.strip():
            para.append(ln.strip())
        elif para:
            break
    return " ".join(para)


def _digest_text(text: str, cfg: dict) -> str:
    max_lines = int(cfg.get("digest_max_lines", 150))
    sections = _sections(text)
    title = next((ln.removeprefix("# ").strip() for ln in text.splitlines() if ln.startswith("# ")), cfg["ssot"])

    def build(excerpt_chars: int) -> list[str]:
        out = [GENERATED_NOTE,
               f"# SSOT Digest — {title}",
               "",
               f"Compact orientation map of `{cfg['ssot']}`. For details read specific sections "
               f"via `{cfg['generated_dir']}/INDEX.md` — do not re-read the whole SSOT.",
               ""]
        for i, (heading, _, content) in enumerate(sections):
            if heading == "(preamble)":
                continue
            out.append(f"**§{i} {heading}**")
            if excerpt_chars:
                p = _first_paragraph(content)
                if p:
                    out.append(f"  {p[:excerpt_chars]}{'…' if len(p) > excerpt_chars else ''}")
            out.append("")
        return out

    for excerpt in (280, 120, 0):
        lines = build(excerpt)
        if len(lines) <= max_lines:
            break
    lines = lines[:max_lines]
    while lines and lines[-1].startswith("**§"):
        lines.pop()
    return "\n".join(lines) + "\n"


def build_views(text: str, cfg: dict) -> dict[str, bytes]:
    """Pure: SSOT source text → {relpath: bytes} for EVERY generated view. The single source of
    truth shared by split/check/round-close, so a partial regen can never leave them inconsistent."""
    sections = _sections(text)
    assert "".join(c for _, _, c in sections) == text, "split is not byte-exact"
    views: dict[str, bytes] = {}
    index_rows = ["| § | Heading | Lines | Bytes | File |", "|---|---|---|---|---|"]
    for i, (heading, start, content) in enumerate(sections):
        fname = f"{i:02d}-{slugify(heading)}.md"
        views[f"sections/{fname}"] = content.encode("utf-8")
        end = start + content.count("\n") - 1
        index_rows.append(
            f"| {i} | {heading} | {start}–{end} | {len(content.encode('utf-8'))} | [{fname}](sections/{fname}) |"
        )
    views["INDEX.md"] = (
        f"""{GENERATED_NOTE}
# SSOT Index — `{cfg['ssot']}`

Read only the sections you need (cite by §-anchor / heading, never by line number).
Source hash: `{_hash(text)[:16]}`

{chr(10).join(index_rows)}
"""
    ).encode("utf-8")
    views["DIGEST.md"] = _digest_text(text, cfg).encode("utf-8")
    views[".hash"] = _hash(text).encode("utf-8")
    return views


def _write_views(outdir: Path, views: dict[str, bytes]) -> None:
    secdir = outdir / "sections"
    secdir.mkdir(parents=True, exist_ok=True)
    expected_sections = {rel.split("/", 1)[1] for rel in views if rel.startswith("sections/")}
    for old in secdir.glob("*.md"):  # drop stale extra section files
        if old.name not in expected_sections:
            old.unlink()
    for rel, data in views.items():
        p = outdir / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(data)


def regenerate(root: Path) -> int:
    """Full deterministic regen of the generated SSOT view set (raises WorkflowError on bad SSOT)."""
    cfg = load_config(root)
    text = _ssot_path(root, cfg).read_text(encoding="utf-8")
    views = build_views(text, cfg)
    _write_views(root / cfg["generated_dir"], views)
    print(f"regenerated {len(views)} SSOT views -> {root / cfg['generated_dir']}")
    return 0


# split/digest are kept as CLI verbs; both do a full regenerate (idempotent) so callers that ran
# `split` then `digest` still work and always leave a consistent view set.
def split(root: Path) -> int:
    return regenerate(root)


def digest(root: Path) -> int:
    return regenerate(root)


def check(root: Path) -> int:
    """Stale iff ANY expected view is missing or byte-differs, or an extra section file lingers —
    not merely the source `.hash` (which split writes even if DIGEST never got generated)."""
    cfg = load_config(root)
    text = _ssot_path(root, cfg).read_text(encoding="utf-8")
    outdir = root / cfg["generated_dir"]
    if not (outdir / ".hash").is_file():
        print("stale: no generated views yet (run split)")
        return 3
    expected = build_views(text, cfg)
    problems: list[str] = []
    for rel, data in expected.items():
        p = outdir / rel
        if not p.is_file():
            problems.append(f"missing {rel}")
        elif p.read_bytes() != data:
            problems.append(f"stale {rel}")
    secdir = outdir / "sections"
    if secdir.is_dir():
        expected_secs = {rel.split("/", 1)[1] for rel in expected if rel.startswith("sections/")}
        for f in sorted(secdir.glob("*.md")):
            if f.name not in expected_secs:
                problems.append(f"extra sections/{f.name}")
    if problems:
        print("stale: " + "; ".join(problems[:8]) + (" …" if len(problems) > 8 else ""))
        return 3
    print("up to date")
    return 0


def main() -> int:
    if len(sys.argv) < 2 or sys.argv[1] not in ("split", "digest", "check"):
        print(__doc__, file=sys.stderr)
        return 1
    root = Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else find_project_root(Path.cwd())
    if root is None:
        print("ssot: no initialized project found", file=sys.stderr)
        return 1
    try:
        return {"split": split, "digest": digest, "check": check}[sys.argv[1]](root)
    except WorkflowError as e:
        print(f"ssot: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
